image: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - develop

skip_tags: true

cache:
#  - node_modules
#  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

init:
  - git config --global core.autocrlf input

environment:
  TRAVIS_OS_NAME_: windows
  GH_TOKEN:
    secure: FPcneTi39lLPzx9eJyempmyiCWbGsJEpQcbDaeqvh48aXqwGmZaIw12iYnLovBu3

install:
  - ps: Install-Product node 12 x64
  - node --version && npm --version
  - npm --global install npm@latest
  - npm --global install asar
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version && npm --version
  - node scripts/package-ci-patch.js package.json %APPVEYOR_BUILD_NUMBER% && cat package.json | grep -i VERSION && cat package.json
  - node scripts/package-ci-patch.js src/package.json %APPVEYOR_BUILD_NUMBER% && cat src/package.json | grep -i VERSION && cat src/package.json
  - npm ci

build_script:
  - 'echo "TRAVIS_OS_NAME_: %TRAVIS_OS_NAME_%"'
  - 'set TRAVIS_TAG=latest-%TRAVIS_OS_NAME_%'
  - 'echo "TRAVIS_TAG: %TRAVIS_TAG%"'
  - 'echo "APPVEYOR_BUILD_ID: %APPVEYOR_BUILD_ID%"'
  - 'echo "APPVEYOR_BUILD_NUMBER: %APPVEYOR_BUILD_NUMBER%"'
  - 'echo "APPVEYOR_BUILD_VERSION: %APPVEYOR_BUILD_VERSION%"'
  - 'echo "APPVEYOR_JOB_ID: %APPVEYOR_JOB_ID%"'
  - 'echo "APPVEYOR_JOB_NAME: %APPVEYOR_JOB_NAME%"'
  - 'echo "APPVEYOR_JOB_NUMBER: %APPVEYOR_JOB_NUMBER%"'
  - 'echo "APPVEYOR_REPO_COMMIT: %APPVEYOR_REPO_COMMIT%"'
  - 'echo "APPVEYOR_ACCOUNT_NAME: %APPVEYOR_ACCOUNT_NAME%"'
  - 'echo "APPVEYOR_PROJECT_NAME: %APPVEYOR_PROJECT_NAME%"'
  - 'echo "APPVEYOR_REPO_NAME: %APPVEYOR_REPO_NAME%"'
  - 'echo "APPVEYOR_REPO_BRANCH: %APPVEYOR_REPO_BRANCH%"'
  - ps: 'if ( $env:APPVEYOR_PULL_REQUEST_NUMBER ) { npm run build:prod } else { npm run package:win }'
  - pwd
  - ls -als
  - ls -als dist
  - ls -Rals dist/node_modules/leveldown || pwd
  - ls -Rals dist/node_modules/sqlite3 || pwd
  - ls -als release || pwd
  - ls -als release/win-unpacked || pwd
  - ls -Rals release/win-unpacked/resources/app.asar.unpacked || pwd
  - (asar l release/win-unpacked/resources/app.asar | grep -i node_modules/leveldown)  || pwd
  - (asar l release/win-unpacked/resources/app.asar | grep -i node_modules/sqlite)  || pwd
  - ps: 'if ( $env:APPVEYOR_PULL_REQUEST_NUMBER ) { pwd } else { Get-ChildItem -File release | Rename-Item -NewName { $_.Name -replace " ","_" } }'
  - ls -als release || pwd

before_deploy:
  - node scripts/release-github.js
deploy:
  tag: '$(TRAVIS_TAG)'
  release: '[$(TRAVIS_TAG)] continuous test build (prerelease)'
  description: 'Appveyor build job: $(APPVEYOR_URL)/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/builds/$(APPVEYOR_BUILD_ID)'
  provider: GitHub
  auth_token:
    secure: FPcneTi39lLPzx9eJyempmyiCWbGsJEpQcbDaeqvh48aXqwGmZaIw12iYnLovBu3
  artifact: /.*\.exe/
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: develop
    APPVEYOR_REPO_TAG: false

artifacts:
  - path: release\*.exe
    name: Thorium

test: off
